### ISSUE TITLE
build failed due to some symbol file not defined or removed

### ISSUE THREAD

**Issue by chinlin0924** [smartdevicelink/rpc_builder_app_android#11]
import com.smartdevicelink.proxy.rpc.GetSystemCapabilityResponse;
                                    ^
  symbol:   class GetSystemCapabilityResponse
  location: package com.smartdevicelink.proxy.rpc

**Comment by askirk** [comment]
This is resolved in latest version.

**Comment by chinlin0924** [comment]
great & thanks!

2018-03-16 22:49 GMT+08:00 Austin Kirk <notifications@github.com>:
