### ISSUE TITLE
Unable to Build in Android Studio

### ISSUE THREAD

**Issue by pcon9000** [smartdevicelink/rpc_builder_app_android#9]
Gradle 'RPCBuilder' project refresh failed
Error:Configuration with name 'default' not found.

One thing I noticed is that the settings Gradle file has:  
include ':app', ':sdl_android'
project (":sdl_android").projectDir = new File("/Users/austinkirk/AndroidStudioProjects/AustinApp/sdl_android")

**Comment by chinlin0924** [comment]
i think this problem can adapt git submodule to maintain instead of hard-codeing the folder path
it is a bit confused to have duplicated android sdl library source code , such as sdl_android_lib, and extra standalone sdl  library cloned outside the sample code.

**Comment by askirk** [comment]
This should be resolved in the latest version, as it uses the gradle compile line for sdl_android instead of manually including the project.
